apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-hostpath-volument
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
      - name: hostpath-storage
        mountPath: /usr/share/nginx/html
        readOnly: true
  volumes:
  - name: hostpath-storage
    hostPath:
      path: /tmp/html
      type: DirectoryOrCreate