apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-local-storage-volume
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
      - name: local-volume
        mountPath: /usr/share/nginx/html
        readOnly: true
  volumes:
  - name: local-volume
    persistentVolumeClaim:
      claimName: local-persistent-volume-claim