apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi