apiVersion: v1
kind: Service
metadata:
  name: nginx-production-service
  labels:
    app: my-nginx
    env: production
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
    role: blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80