apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  labels:
    app: my-nginx
    env: test
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
    role: green
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
